package software.simple.solutions.framework.core.components;

import com.vaadin.ui.Alignment;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

import software.simple.solutions.framework.core.util.NumberUtil;
import software.simple.solutions.framework.core.util.PropertyResolver;

public class CDiscreetDateField extends HorizontalLayout implements IField {

	private static final long serialVersionUID = 4666354050053018420L;

	private CDiscreetNumberField dayFld;
	private Label seperator2;
	private CDiscreetNumberField monthFld;
	private Label seperator1;
	private CDiscreetNumberField yearFld;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public CDiscreetDateField() {
		buildMainLayout();
	}

	public Long getYear() {
		return NumberUtil.getLong(yearFld.getValue());
	}

	public Long getMonth() {
		return NumberUtil.getLong(monthFld.getValue());
	}

	public Long getDay() {
		return NumberUtil.getLong(dayFld.getValue());
	}

	private HorizontalLayout buildMainLayout() {
		setSpacing(true);

		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");

		// yearFld
		yearFld = new CDiscreetNumberField();
		yearFld.setWidth("50px");
		yearFld.setHeight("-1px");
		addComponent(yearFld);

		// l1
		seperator1 = new Label();
		seperator1.setWidth("-1px");
		seperator1.setHeight("-1px");
		seperator1.setValue("-");
		addComponent(seperator1);
		setComponentAlignment(seperator1, new Alignment(48));

		// monthFld
		monthFld = new CDiscreetNumberField();
		monthFld.setWidth("30px");
		monthFld.setHeight("-1px");
		addComponent(monthFld);

		// l2
		seperator2 = new Label();
		seperator2.setWidth("-1px");
		seperator2.setHeight("-1px");
		seperator2.setValue("-");
		addComponent(seperator2);
		setComponentAlignment(seperator2, new Alignment(48));

		// dayFld
		dayFld = new CDiscreetNumberField();
		dayFld.setWidth("30px");
		dayFld.setHeight("-1px");
		addComponent(dayFld);

		return this;
	}

	@Override
	public void setCaptionByKey(String key) {
		super.setCaption(PropertyResolver.getPropertyValueByLocale(key, getLocale()));
	}

	public void clear() {
		dayFld.clear();
		monthFld.clear();
		yearFld.clear();
	}

	public void setValue(Long day, Long month, Long year) {
		dayFld.setLongValue(day);
		monthFld.setLongValue(month);
		yearFld.setLongValue(year);
	}

	@Override
	public boolean isThisRequired() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void setRequired() {
		dayFld.setRequired();
		monthFld.setRequired();
		yearFld.setRequired();
	}

	@Override
	public void setDefault() {
		dayFld.setDefault();
		monthFld.setDefault();
		yearFld.setDefault();
	}

	@Override
	public Object getValue() {
		// TODO Auto-generated method stub
		return null;
	}

}
